cn331project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('courses/', include('courses.urls')),

]

courses/urls.py
from django.urls import path
from . import views
from .models import CourseModel

app_name="courses"
urlpatterns =[
    path('', views.index, name="index"),
    path('<str:code>', views.course, name="course"),
    path('<str:code>/takecourse', views.takecourse, name="takecourse"),
    path('<str:code>/rmcourse', views.rmcourse, name="rmcourse"),
    ]

home/urls.py
from django.urls import path

from . import views

app_name="home"
urlpatterns = [
    path("", views.index, name="index"),
]

users/urls.py
from django.urls import path

from . import views

app_name="users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

courses/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CourseModel(models.Model):
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=64)
    semester = models.IntegerField()
    year = models.IntegerField()
    seat = models.IntegerField()
    status = models.BooleanField()
    student = models.ManyToManyField(User, blank = True, related_name = "students")

    def __str__(self):
        return f"{self.code} {self.name}"

home/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

courses/views.py
import courses
from django.shortcuts import render, get_object_or_404
from .models import CourseModel
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def index(request):
    return render(request, "courses/index.html", {"courses" : CourseModel.objects.all()})

def course(request, code):
    course = CourseModel.objects.get(code=code)
    students = course.student.all()
    now = students.count()
    return render(request, "courses/course.html", {'course': course ,'students': students ,'now': now})

def takecourse(request, code):
    if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("users:login"))

    course = CourseModel.objects.get(code=code)
    if request.user not in course.student.all():
        course.student.add(request.user)
    return HttpResponseRedirect(reverse("courses:course", args=(code,)))

def rmcourse(request, code):
    if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("users:login"))

    course = CourseModel.objects.get(code=code)
    if request.user in course.student.all():
        course.student.remove(request.user)
    return HttpResponseRedirect(reverse("courses:course", args=(code,)))

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.

def index(request):
        return render(request, "home/index.html")

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import courses

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    else:
        get_subject = request.user.students.all()
        return render(request, "users/index.html",{
        "subject":get_subject,
    })
            
   

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            messages.warning(request, "Invalid credential.")
            return render(request, "users/login.html", {
                "messages": messages.get_messages(request)
            })


def logout_view(request):
    logout(request)
    return render(request, "users/login.html")

courses/templates/courses/course.html
{% extends "courses/layout.html" %}

{% block body %}

    <h1>{{ course.code }} {{ course.name }}</h1>
    <ul><br>
    <li>{{ course.semester }} / {{ course.year }}</li>
    <li>capacity : {{now}} / {{ course.seat }}</li>
    <li>Status: {{ course.status }}</li>
    </ul><br>
     {% if perms.app_label.can_do_something %}
    <h2>Student now : {{now}}</h2>

    <ul>
        {% for i in students %}
        <li>{{ i.first_name }} {{ i.last_name }}</li>
        {% empty %}
        <li>No studenet </li>
        {% endfor %}<br>
    </ul>
    {% else %}
        {% if request.user in students %}
            <h3>Already register</h3><br>
        {% endif %}
        {% if course.status == True %}
        {% if course.seat > now %}
            <div class="container">
                <div class="card">
                    <div class="cardcontent">
                    <h3><a href="{% url 'courses:takecourse' course.code %}">Take this Course</a></h3>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="card">
                    <div class="cardcontent">
                    <h3><a href="{% url 'courses:rmcourse' course.code %}">Remove this Course</a></h3>
                    </div>
                </div>
            </div>
        <br>
        {% else %}
        <h3>THIS COURSE IS FULL</h3>
        {% endif %}
        {% else %}
        <h3>THIS COURSE IS OFF</h3>
        {% endif %}
        <br>
    {% endif %}

    <div class="container">
        <div class="card">
            <div class="cardcontent">
            <h4><a href="{% url "courses:index" %}">Back to Course List</a></h3>
            </div>
        </div>
    </div>

{% endblock %}

courses/templates/courses/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Courses</title>
        <link rel="stylesheet" type="text/css" href="{% static '/css/courselist.css' %}">
    </head>
        <body>
            {% block body %}
    <q>Course List</q>
    <ul>
    {% for course in courses %}
    <div class="container">
        <div class="card">
                <div class="cardcontent">
                 <li><a href="{% url "courses:course" course.code %}"> {{ course }}</a></li>
                </div>
        </div>
    </div>
    {% endfor %}

    </ul>
    <p><a href="{% url 'users:index' %}">main</a></p>
{% endblock %}

        </body>
</html>

courses/templates/courses/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Courses</title>
        <link rel="stylesheet" type="text/css" href="{% static '/css/course.css' %}">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

home/templates/home/index.html
{%load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Home</title>
        <link rel="stylesheet" type="text/css" href="{% static '/css/cube.css' %}">
    </head>
    <body>
        <div class="foo">
                        <span class="letter" data-letter="W">W</span>
                        <span class="letter" data-letter="E">E</span>
                        <span class="letter" data-letter="L">L</span>
                        <span class="letter" data-letter="C">C</span>
                        <span class="letter" data-letter="O">O</span>
                        <span class="letter" data-letter="M">M</span>
                        <span class="letter" data-letter="E">E</span>
                        <br><span class="letter" data-letter="T">T</span>
                        <span class="letter" data-letter="O">O</span>
            <div class="container">
                <div class="card">
            <br><a href="{% url 'users:logout' %}"><span class="letter" data-letter="L O G I N">L O G I N</a></span>
                </div>
            </div>
          </div>
    </body>

users/templates/users/index.html
{% extends "users/layout.html" %}

{% block body %}

    <h1>Welcome, {{ request.user.first_name }}</h1>

    <ul>
        <br>
        <p>Username: {{ request.user.username }}</p>
        <p>Email: {{ request.user.email }}</p>
    </ul>
    <br>
    {% if perms.app_label.can_do_something %}
    <div class="container">
        <div class="card">
            <div class="cardcontent">
            <a href="{% url 'admin:index' %}">manage courses</a><br>
            </div>
        </div>
    </div>
    {% else %}
    <br>
    <h2>Registation</h2>
    <br>
    {% for x in subject  %}
        <li>{{ x }}</li>
    {% endfor %}
    <br>
    {% endif %}
     <div class="container">
        <div class="card">
            <div class="cardcontent">
            <a href="{% url 'courses:index' %}">Course list</a><br>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="card">
            <div class="cardcontent">
            <a href="{% url 'users:logout' %}">Log out</a>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>login</title>
        <link rel="stylesheet" type="text/css" href="{% static '/css/index.css' %}">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>login</title>
        <link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
    </head>
    {% block body %}
      <form method="post" action="{% url 'users:login' %}" id="login-form" class="login-form" autocomplete="off" role="main">
          {% csrf_token %}
          <h1 class="a11y-hidden">Login Form</h1>
            <div>
              <label class="label-email">
                <input type="text" name="username" placeholder="Username">
                <span class="required">Username</span>
              </label>
              <label class="label-password">
                <input type="password" name="password" placeholder="Password">
                <span class="required">Password</span>
              </label>
            </div>
            <input type="submit" value="Login" >
            <figure aria-hidden="true">
              <div class="person-body"></div>
              <div class="neck skin"></div>
              <div class="head skin">
              <div class="eyes"></div>
              <div class="mouth"></div>
              </div>
              <div class="hair"></div>
              <div class="ears"></div>
              <div class="shirt-1"></div>
              <div class="shirt-2"></div>
            </figure>
          {% if messages %}
          {% for message in messages %}
          <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
    {% endif %}

      </form>

{% endblock %}